version: '3.4'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:80
      - 443:443
    volumes:
      - .:/work
      - ./docker/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/certs:/etc/certs

  alpha:
    image: httpd
    ports:
      - 8081:80
    volumes:
      - ./docker/alpha/usr/local/apache2/htdocs:/usr/local/apache2/htdocs
      - ./docker/alpha/usr/local/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./etc/certs:/etc/certs

  beta:
    image: httpd
    ports:
      - 8082:80
    volumes:
      - ./docker/beta/usr/local/apache2/htdocs:/usr/local/apache2/htdocs
      - ./docker/beta/usr/local/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./etc/certs:/etc/certs

