version: '3.4'
services:
  nginx:
    image: nginx:1.15.2
    ports:
      - 8080:80
    volumes:
      - .:/work

  alpha:
    image: httpd
    ports:
      - 8081:80
    volumes:
      - ./docker/alpha/usr/local/apache2/htdocs:/usr/local/apache2/htdocs

  beta:
    image: httpd
    ports:
      - 8082:80
    volumes:
      - ./docker/beta/usr/local/apache2/htdocs:/usr/local/apache2/htdocs

